spring:
  application:
    name: spm_backend
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
  main:
    allow-bean-definition-overriding: true
minio:
  endpoint: http://localhost:9000           # 替换为您的 MinIO 服务地址
  access-key: 2IapYfTR6v67wch7DsBK               # 替换为您的 MinIO Access Key
  secret-key: 1EMUw3wEsDfPSoXQGWXEjupsKwb89ByIdfCdkVMn               # 替换为您的 MinIO Secret Key
  bucket-name: spm              # 替换为您想使用的 Bucket 名称
security:
  paths:
    publicRoutes:
      - /doc.html
      - /webjars/**
      - /v3/api-docs/**
      - /auth/**
    authenticated:
      - /user/**  # 需要登录的路径
      - /course/**
      - /paper/**
      - /question/**
      - /submit/**
# 在生产环境中，需要禁用swagger
springdoc:
  api-docs:
    enabled: true
knife4j:
  setting:
    language: zh_cn
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  forward-headers-strategy: framework