spring:
  application:
    name: spm_backend
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/flappy_bird?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
# 在生产环境中，需要禁用swagger
springdoc:
  api-docs:
    enabled: true
knife4j:
  setting:
    language: zh_cn
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  forward-headers-strategy: framework